config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :forums
  resources :videos
  resources :songs
  resources :blogs do
    resources :comments
  end
  root "landing#index"
  get 'terms', :to => 'terms#terms_services'
  get 'landing', :to => 'landing#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_many :comments
    acts_as_punchable
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :blog
    belongs_to :song
    belongs_to :video
    belongs_to :forum
end

app/models/forum.rb
class Forum < ApplicationRecord
    belongs_to :topic
    has_many :comments
    acts_as_punchable
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :topics
    has_many :comments
    acts_as_punchable
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :blogs
    has_many :videos
    has_many :songs
    has_many :forums
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  has_many :videos
  has_many :songs
  has_many :forums
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
    belongs_to :topics
    has_many :comments
    acts_as_punchable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_blog, only: [:show, :edit, :update, :destroy,]


    def index
        @blogs = Blog.all.order("created_at DESC")
    end

    def show
        @blog.punch(request)
    end

    def new
        @blog = current_user.blogs.build
        @topics = Topic.all
    end

    def create
        @blog = current_user.blogs.build(blog_params)
        
        if @blog.save!
            redirect_to @blog, notice: "Yesss! It was posted!"
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @blog.update(blog_params)
            redirect_to @blog, notice: "Congrats! Blog was updated!"
        else
            render 'edit'
        end
    end

    def destroy
        @blog.destroy
        redirect_to root_path
    end


    private
    def blog_params
        params.require(:blog).permit(:title, :content, :topic_id)
    end

    def find_blog
        @blog = Blog.find(params[:id])
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @blog = Blog.find(params[:blog_id])

        @comment = @blog.comments.create!(params[:comment].permit(:body))
        @comment.save
        byebug
        redirect_to blog_path(@blog)
      end
    
      def destroy
        @blog = Blog.find(params[:blog_id])
        @comment = @blog.comments.find(params[:id])
        @comment.destroy
    
        redirect_to blog_path(@blog)
      end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_forum, only: [:show, :edit, :update, :destroy,]


    def index
        @forums = Forum.all.order("created_at DESC")
    end

    def show
        @forum.punch(request)
    end

    def new
        @forum = current_user.forums.build
        @topics = Topic.all
    end

    def create
        @forum = current_user.forums.build(forum_params)

        if @forum.save
            redirect_to @forum, notice: "Yesss! It was posted!"
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @forum.update(forum_params)
            redirect_to @forum, notice: "Congrats! Forum was updated!"
        else
            render 'edit'
        end
    end

    def destroy
        @forum.destroy
        redirect_to root_path
    end


    private

    def forum_params
        params.require(:forum).permit(:question, :description, :topic_id)
    end

    def find_forum
        @forum = Forum.find(params[:id])
    end
    
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

    def index
        @songs = Song.all
        @videos = Video.all
        @blogs = Blog.all
        @objects = @songs + @videos + @blogs 
        # @objects = @objects.all.sort_by {|obj| obj.hits}
    end


end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_song, only: [:show, :edit, :update, :destroy,]


    def index
        @songs = Song.all.order("created_at DESC")
    end

    def show
        @song.punch(request)
    end

    def new
        @song = current_user.songs.build
    end

    def create
        @song = current_user.songs.build(song_params)

        if @song.save
            redirect_to @song, notice: "Yesss! It was posted!"
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @song.update(song_params)
            redirect_to @song, notice: "Congrats! Song was updated!"
        else
            render 'edit'
        end
    end

    def destroy
        @song.destroy
        redirect_to root_path
    end


    private

    def song_params
        params.require(:song).permit(:title, :attachment)
    end

    def find_blog
        @song = Song.find(params[:id])
    end
    
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
    def index
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def show
        @user = User.find(params[:id])

    end

    def edit
        @user = User.find(params[:id])
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_video, only: [:show, :edit, :update, :destroy,]

    def index
        @videos = Video.all.order("created_at DESC")
    end

    def show
        @video.punch(request)
    end

    def new
        @video = current_user.videos.build
    end

    def create
        @video = current_user.videos.build(video_params)

        if @video.save
            redirect_to @video, notice: "Yesss! It was posted!"
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @video.update(video_params)
            redirect_to @video, notice: "Congrats! Video was updated!"
        else
            render 'edit'
        end
    end

    def destroy
        @video.destroy
        redirect_to root_path
    end


    private

    def video_params
        params.require(:video).permit(:title, :attachment)
    end

    def find_video
        @video = Video.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/blogs/_form.html.erb
<%= form_for @blog do |f| %>
  <% if @blog.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@blog.errors.count, "error") %> stopped this blog from saving</h2>
      <ul>
        <%= @blog.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>

  <% end %>

  <div class="title">
    <%= f.text_field :title, placeholder: "Title", class: 'title_input' %>
  </div>
  
  <div>
    <%= f.select :topic_id, options_from_collection_for_select(Topic.all, :id, :name), class: 'category_input' %>
  </div>

  <div class="description">
    <%= f.text_area :content, placeholder: "Description", class: 'description_input'%>
  </div>

  <div class="term">
      <%# <%= f.check_box :content, class: 'term_check_box' %>
     
      <p class="term_text">I have read and agree to the terms by checking off this box.</p>
      <%= link_to 'Terms', terms_path, class: 'term_link' %>
    </div>

  <div>
    <%= f.submit class: "csubmit" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div id="page_wrapper">
  <h1>Fix Blog</h1>

  <%= render 'form' %>
</div>

app/views/blogs/index.html.erb
<% @blogs.each do |blog| %>
  <div class="blog_wrapper">
    <h2 class="title"><%= link_to blog.title, blog %></h2>
    <p class="body"><%= truncate(blog.content, length:100) %></p>
    <p class="date"><%= time_ago_in_words(blog.created_at) %> ago</p>
  </div>
<% end %>

app/views/blogs/new.html.erb
<div class="main_header">
  <div class="text">
      <h1>Singing Scientific</h1>
      <h2 class="subtitle">Science Through The Arts</h2>
  </div>
  <div class="topics">
      <div class="topic1">
        <%= image_tag("topic.jpg") %>
        <p>Topic</p>
      </div>
      <div class="topic1">
        <%= image_tag("topic1.jpg") %>
        <p>Topic</p>
      </div>
      <div class="topic1">
        <%= image_tag("topic2.jpg") %>
        <p>Topic</p>
      </div>
      <div class="topic1">
        <%= image_tag("topic3.jpg") %>
        <p>Topic</p>
      </div>
      <div class="topic1">
        <%= image_tag("topic4.jpg") %>
        <p>Topic</p>
      </div>
      <div class="topic1">
        <%= image_tag("topic5.jpg") %>
        <p>Topic</p>
      </div>
      <div class="topic1">
        <%= image_tag("topic6.jpg") %>
        <p>Topic</p>
      </div>
      <div class="topic1">
        <%= image_tag("topic1.jpg") %>
        <p>Topic</p>
      </div>
      <div class="topic1">
        <%= image_tag("topic7.jpg") %>
        <p>Topic</p>
      </div>
  </div> 
</div>

  <div class="blogs_wrapper"> 
    <div class="blog_body">
      <%= render 'form' %>
    </div> 
  </div>

app/views/blogs/show.html.erb
<div class="main_header">
  <div class="text">
      <h1>Singing Scientific</h1>
      <h2 class="subtitle">Science Through The Arts</h2>
  </div>
  <div class="topics">
      <div class="topic">
        <%= image_tag("topic.jpg") %>
        <p>Topic</p>
      </div>
      <div class="topic1">
        <%= image_tag("topic1.jpg") %>
        <p>Topic</p>
      </div>
      <div class="topic1">
        <%= image_tag("topic2.jpg") %>
        <p>Topic</p>
      </div>
      <div class="topic1">
        <%= image_tag("topic3.jpg") %>
        <p>Topic</p>
      </div>
      <div class="topic1">
        <%= image_tag("topic4.jpg") %>
        <p>Topic</p>
      </div>
      <div class="topic1">
        <%= image_tag("topic5.jpg") %>
        <p>Topic</p>
      </div>
      <div class="topic1">
        <%= image_tag("topic6.jpg") %>
        <p>Topic</p>
      </div>
      <div class="topic1">
        <%= image_tag("topic1.jpg") %>
        <p>Topic</p>
      </div>
      <div class="topic1">
        <%= image_tag("topic7.jpg") %>
        <p>Topic</p>
      </div>
  </div> 
</div>

<div class="blog_content">
  <h1 class="blog_title">
    <%= @blog.title%>
  </h1>

    <div class="blog_description">
      <%= @blog.content %>
    </div>

  <div class="comments">
    <h2 class="response_count">Responses (<%= @blog.comments.count %>)</h2>
    <%= image_tag 'registry1.jpg', class: 'comment_image comment_inline' %>
    <%= render "comments/form" %>

    <hr class="comment_line">

    <div class="comments_section">
      <%= render @blog.comments %>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="comment_inline">
  <%= form_for([@blog, @blog.comments.build]) do |f| %>
    
    <p>
      <%= f.text_area :body, class: 'comment_input ' %>
    </p>
    <br>
  <% end %>
</div> 

app/views/songs/_form.html.erb
<%= form_for @song do |f| %>
  <% if @song.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@song.errors.count, "error") %> stopped this song from saving</h2>
      <ul>
        <%= @song.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>

  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :attachment %><br>
    <%= f.text_area :attachment %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/songs/new.html.erb
<div id="songs_wrapper">
  <h1>Create A Song</h1>

  <%= render 'form' %>
</div>

app/views/videos/_form.html.erb
<%= form_for @video do |f| %>
  <% if @video.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(video.errors.count, "error") %> stopped this song from saving</h2>
      <ul>
        <%= @video.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>

  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :attachment %><br>
    <%= f.text_area :attachment %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/videos/new.html.erb
<div id="videos_wrapper">
  <h1>Create A Video</h1>

  <%= render 'form' %>
</div>